### ISSUE TITLE
Newly added overwrite (DATA) missing from token list

### ISSUE THREAD

**Issue by jtakalai** [xdaichain/omnibridge#179] opened 2021-03-15 14:07 UTC
Repro:
* open https://omni.xdaichain.com/
* open ETH mainnet token select dropdown (left from label "STAKE")
* type DATA to search field

Expected:
* DATA token appears in the suggestions

Actual:
* only BCDT appears

It worked as expected before the override from https://github.com/xdaichain/omnibridge/pull/171

**Comment by jtakalai** [comment] 2021-03-15 14:14
Clue:

UI sends a POST request to https://api.thegraph.com/subgraphs/name/raid-guild/mainnet-omnibridge with body
```
  query homeTokens {
    tokens(where: { homeAddress_contains: "0x" }, first: 1000) {
      chainId: homeChainId
      address: homeAddress
      name: homeName
      symbol
      decimals
    }
  }
``` 
And the response is
```
{
  "data": {
    "tokens": [
      {
        "address": "0x1a5f9352af8af974bfc03399e3767df6370d82e4",
        "chainId": 1,
        "decimals": 18,
        "name": "OWL Token",
        "symbol": "OWL"
      },
      {
        "address": "0xc3589f56b6869824804a5ea29f2c9886af1b0fce",
        "chainId": 1,
        "decimals": 18,
        "name": "Honey",
        "symbol": "HNY"
      },
      {
        "address": "0xe1ca72ff3434b131765c62cbcbc26060f7aba03d",
        "chainId": 1,
        "decimals": 18,
        "name": "MOONs on Ethereum",
        "symbol": "MOON"
      }
    ]
  }
}
```

This response can be verified with the playground at https://thegraph.com/explorer/subgraph/raid-guild/mainnet-omnibridge

These are all other tokens present in https://github.com/xdaichain/omnibridge/blob/master/packages/subgraph/config/mainnet.json except DATA. Maybe that has something to do with the problem?

**Comment by hpihkala** [comment] 2021-03-15 14:14
Ping @dan13ram

**Comment by dan13ram** [comment] 2021-03-15 14:43
Thank you @jtakalai and @hpihkala for raising this issue. We have discovered a bug in the subgraphs that arose from changes unrelated to your PR. 

This has been fixed now and deployed. The subgraphs will take some time to sync but once synced you should be able to choose the DATA token from the drop-down. 

You can check the status at:
https://thegraph.com/explorer/subgraph/raid-guild/xdai-omnibridge?version=pending
https://thegraph.com/explorer/subgraph/raid-guild/mainnet-omnibridge?version=pending

I shall update the PR once the subgraphs have finished syncing and the issue is resolved.

**Comment by hpihkala** [comment] 2021-03-15 14:46
@dan13ram Fantastic, thanks for the speedy resolution! We'll try it out once synced and get back to you. 

In the meanwhile, I noticed another issue re gas estimation for `approve`. I'm working to confirm the steps to reproduce and open another issue. :)

**Comment by dan13ram** [comment] 2021-03-15 14:51
Sure @hpihkala, We use `ethers` with `web3modal`, and let the wallet do the estimation. So if there is an error in gas estimation, I wonder if the issue is with the wallet. 

In any case, please raise the issue and we shall see what can be done.

**Comment by hpihkala** [comment] 2021-03-15 17:30
@dan13ram the subgraphs just finished syncing. But unfortunately `DATA` is still not coming up from the queries. 😭

The query referred to by @jtakalai above still gives the same result, with no `DATA` in there.

**Comment by hpihkala** [comment] 2021-03-15 17:43
To be clear, the issue described applies when the UI is in Ethereum -> xDai direction.

For xDai -> Ethereum direction, `DATA` shows up in the UI, but it's the _wrong one_. It's showing the token auto-generated by OmniBridge when we were playing around with it, not the custom one that should now be shown.

Could it somehow be causing this issue that the old auto-generated DATA exists as well as the custom defined one? Both obviously relate to the same mainnet token, but have different mediators and different sidechain tokens.

**Comment by dan13ram** [comment] 2021-03-16 01:33
We made some changes to the subgraph relating to overrides, where we are fetching the direction of the bridging on-the-go and setting overrides. There was another minor bug that was incorrectly setting the direction for xDai -> Mainnet.

**Closed** 2021-03-16 11:58 UTC
